In [3]:
import numpy as np

In [4]:
data = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

a = np.array(data)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
a.dtype

dtype('int32')

In [6]:
a = a.astype(np.float32) # a = a.astype('floatg32')
a

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float32)

In [7]:
a[0][1]

2.0

In [8]:
a[0]

array([1., 2., 3.], dtype=float32)

In [9]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [10]:
np.arange(1, 10).reshape(3, 3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
np.arange(1, 13).reshape(3, 2, 2)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [13]:
np.nan + 10

nan

In [14]:
a[0][1] = np.nan

In [15]:
a

array([[ 1., nan,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.]], dtype=float32)

In [16]:
a = np.linspace(1, 10, 10)
a

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])